### ISSUE TITLE
forked file is possibly missing code in a file and has extra code in another.

### ISSUE THREAD

**Issue by lcorr8** [learn-co-curriculum/method-scope-lab#14]
1. Line 27 referred to in the below paragraph of the README was not in the forked file. 

"This error is occurring because the code inside the #catch_phrase method is trying to use the phrase variable but we defined this variable on line 27 of our test. In other words, this variable is being defined outside of the method. Our method doesn't have access to it! It is out of scope. Let's fix it!"

-0-
1. The Read Me asks you to make the following change, but this change is already coded in the forked file.

```
Change the test in spec/catch_phrase_spec.rb to match the following:
require "spec_helper"
describe "#catch_phrase" do 
  it "puts out a catch phrase" do 
    phrase = "It's-a me, Mario!"
    expect{catch_phrase(phrase)}.to output("It's-a me, Mario!\n").to_stdout
  end
end
```

**Comment by AnnJohn** [comment]
Hi @lcorr8 the spec actually doesn't have the correct code. 

Here's what the spec_helper says:
    expect{catch_phrase}.to output("It's-a me, Mario!\n").to_stdout

That's different from how you're asked to update it in the Readme. 

Thanks!
