### ISSUE TITLE
Isn't the solution wrong?

### ISSUE THREAD

**Issue by marineb** [learn-co-curriculum/method-scope-lab#20]
I don't believe `#catch_phrase` is supposed to have an argument. In order to pass, the string must be defined within `#catch_phrase`. Right? Test below.  

```
describe "#catch_phrase" do 
  it "puts out a catch phrase" do 
    phrase = "It's-a me, Mario!"
    expect{catch_phrase}.to output("It's-a me, Mario!\n").to_stdout
  end
end
```

**Comment by AnnJohn** [comment]
hi @marineb could you use Ask a Question first and someone from our team will help you out this? If there is a problem with the specs, then we'll raise an issue here. Thanks!

**Comment by marineb** [comment]
Sorry about that. Sounds good.
