### ISSUE TITLE
Test not running correctly?

### ISSUE THREAD

**Issue by bmcilhenny** [learn-co-curriculum/method-scope-lab#21]
Shouldn't the 'expect{puts status}.to raise_error(NameError)' in the spec file pass when you comment out the #puts status in the rescue_princess_peach.rb file? Instead the test doesn't even run. It should run the test suite and return this to the console:
![screen shot 2017-09-19 at 10 27 02 pm](https://user-images.githubusercontent.com/28611492/30624184-e55aab7c-9d89-11e7-88ff-1ea6719f0843.png)

but it gets an error when the puts status is commented back in and outputs this to the console:

![screen shot 2017-09-19 at 10 26 50 pm](https://user-images.githubusercontent.com/28611492/30624181-deaa5688-9d89-11e7-9031-bff9007926ac.png)

**Comment by sgharms** [comment]
I think you're not quite understanding the way this test is working. This would be great to bring up in an [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson). Keep at it and good luck!
