### ISSUE TITLE
The first instruction in Part II is difficult to understand.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/method-scope-lab#22]
In "Part II: Understanding Method Scope" and in the rescue_princess_peach.rb file, there are instructions that are worded a bit strangely. In the README, it says that we need to "Comment back in the following lines..." and in the file, we are supposed to "Comment the below back in to see method scope in action!"

I did not understand what it meant at first, since the lines in question were already commented out. After reading further in the README, I realized that it meant that we are supposed to un-comment the lines. 

I would simply suggest replacing "Comment back in" and "Comment the below back in" with "Un-comment" and "Un-comment the lines below", respectively. This should prevent others from experiencing the same confusion that I had with the instructions.

As always, thanks for looking into this!
Sdcrouse

**Comment by cjbrock** [comment]
Hey @Sdcrouse! I agree - that wording was unnecessarily confusing. I've made your suggested changes. As always, thanks for taking your time to make Learn a better place. <3 
// Corinna

**Comment by Sdcrouse** [comment]
You're welcome! Thanks for getting back to me :)

Sdcrouse
