### ISSUE TITLE
The instructions inside the rescue_princess_peach.rb file are a little confusing.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/method-scope-lab#23]
Hello! I hate to reopen an issue, but the instructions inside the rescue_princess_peach.rb file are a little difficult to understand. Currently, they say that we have to "Comment the below back in to see method scope in action!" This is confusing because the lines in question are already commented out.

The instructions would be much clearer if they were re-written like this: "Un-comment the lines below to see method scope in action!"

Thanks again for looking into this and for taking care of one of the issues I brought up earlier.

---Sdcrouse

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
