### ISSUE TITLE
rescue princess test incorrectly passing

### ISSUE THREAD

**Issue by disarrangedorder** [learn-co-curriculum/method-scope-lab#24]
the second rescue_princess_peach test is passing even tho i haven't even gotten to that part.

**Comment by sgharms** [comment]
Hi, @disarrangedorder. This lab is a little different in that `rescue_princess_peach` lab never breaks. In Part II we'll experiment with failing conditions of scope by editing the source file. Keep working through and you'll see why this is OK.
