### ISSUE TITLE
rescue_princess_peach.rb

### ISSUE THREAD

**Issue by eaud** [learn-co-curriculum/method-scope-lab#6]
2nd spec (puts status => error) passes as a test on its own - so the student following the instructions would need to uncomment lines 11-12 of ...peach.rb to follow the instructions, but then (not documented in the instructions) need to recomment them out to submit it as completed.

**Comment by SophieDeBenedetto** [comment]
hi @eaud, 

I add in an explicit instructions to re-comment on lines 11 and 12 of that file. The readme already contains explicit instructions when it is required of them to un-comment out those lines the first time. 

Thanks for raising an issue!
